#!/usr/bin/env python3
"""RESEARCH ONLY -- cheap_gate for the dual-slot concurrent-position candidate
(docs/model_contracts/eth_candidate_dual_slot_concurrent_positions_contract_20260816.md). Before
building a full replay engine that tracks two concurrent positions, estimate an UPPER BOUND on the
opportunity: reuse the already-saved zig075 episode labels (docs/experiments/
eth_candidate_conformal_veto_episode_labels_20260816.md -- causal standalone-simulation `full` net
return per quality-gate-passing signal episode, fee/slip already included) and re-derive which of
those episodes were blocked by an already-open h48qual position (same classification logic as the
2026-08-16 frequency check that motivated this candidate). Sum the counterfactual `full` returns of
just the blocked-by-h48qual subset.

This is a deliberate overestimate: it ignores the aggregate NOTIONAL_CAP constraint the real
mechanism would impose (a second concurrent position gets whatever budget remains, not full size),
ignores compounding/path effects, and assumes every blocked episode could have been taken at
standalone size. If even this generous upper bound is small or negative, the full engine isn't worth
building.

VAL ONLY. OOS-Q1/OOS-Q2 not opened by this script (episode labels for OOS were never generated by
the conformal-veto candidate either -- only 2025q1-q3 train pool + val).

fresh_forward_bar_by_bar=true. trade_ledgers_used_as_input=false (the zig075 episode labels are
freshly-simulated counterfactuals, not replayed saved trades; the h48qual holding intervals come
from a live G0 replay run in this script). saved_parent_exit_timestamps_used=false.
future_rows_used_for_entry=false.

Does NOT touch trading_bot.py / trading_bot_modules/omega4_6_1_live.py /
trading_bot_modules/runtime_config.py / .env. Does NOT modify any imported module. No GPU needed
for this script's own logic (no model inference here -- the G0 replay it calls does use CPU
inference internally).
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
if str(ROOT / "scripts") not in sys.path:
    sys.path.insert(0, str(ROOT / "scripts"))

import train_eval_omega1_2_tabm_diffusion_risk_20260603 as omega  # noqa: E402
import replay_omega4_6_1_greedy_router_20260706 as greedy  # noqa: E402
import research_eth_omega461_exit_sweep_20260721 as sweep  # noqa: E402
import research_eth_omega461_exit_head_portfolio_asymmetric_20260813 as portfolio  # noqa: E402
import eth_omega461_multiwindow_confirmation_gate_20260814 as gate  # noqa: E402
import research_eth_omega461_regime_aware_exit_head_uptrend_guard_20260814 as guard  # noqa: E402
import research_eth_omega461_zig075_short_entry_veto_sustained_uptrend_20260814 as o4  # noqa: E402

OUT_DIR = ROOT / "tmp/causal_regen_20260516/eth_candidate_dual_slot_cheap_gate_20260816"
LABEL_DIR = ROOT / "tmp/causal_regen_20260516/eth_candidate_conformal_veto_episode_labels_20260816"
DEVICE = portfolio.DEVICE
WINDOW = "val"


def log(msg: str) -> None:
    print(f"[dual_slot_cheap_gate] {msg}", flush=True)


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    device = DEVICE
    fee, slip = omega._load_fee_slip()

    log("=== stage=detector_build ===")
    score_by_base, robustness_thresholds, threshold = guard.build_detector()
    windows = gate.load_all_windows()

    log("=== stage=g0_replay (to get h48qual's actual held intervals) ===")
    aligned_frame, components, prep_diag = guard.prepare_regime_aware_components(WINDOW, windows, score_by_base, threshold, OUT_DIR, device)
    mask, _ = guard._detector_mask_for_frame(aligned_frame, WINDOW, score_by_base, threshold)
    veto_components = o4._attach_veto_mask(components, mask)
    diag, ledger = o4.greedy_replay_entry_veto(aligned_frame, veto_components, fee=fee, slip=slip, cost_mult=sweep.COST_MULT, device=device)
    baseline_metrics = portfolio._ledger_metrics(ledger)
    log(f"  G0 no_gate={baseline_metrics['pnl']:.2f}%/{baseline_metrics['mdd']:.2f}%/{baseline_metrics['trades']}")

    n = len(aligned_frame)
    held_by = np.array([""] * n, dtype=object)
    for _, r in ledger.iterrows():
        ei, xi = int(r["entry_i"]), int(r["exit_i"])
        held_by[ei:xi + 1] = r["source_component"]

    log("=== stage=load_zig075_episode_labels ===")
    labels = pd.read_parquet(LABEL_DIR / f"episode_labels_{WINDOW}_zig075.parquet")
    entry_signal_i = labels["entry_signal_i"].to_numpy(dtype=np.int64)
    entry_i = np.clip(entry_signal_i + 1, 0, n - 1)

    blocked_h48 = held_by[entry_i] == "h48qual"
    blocked_self = held_by[entry_i] == "zig075"
    free = held_by[entry_i] == ""

    log(f"  zig075 episodes: total={len(labels)} blocked_by_h48qual={int(blocked_h48.sum())} blocked_by_self={int(blocked_self.sum())} free={int(free.sum())}")

    subset = labels[blocked_h48]
    full = subset["full"].to_numpy(dtype=np.float64)
    adverse = subset["adverse"].to_numpy(dtype=np.float64)

    upper_bound = {
        "n_blocked_episodes": int(len(subset)),
        "sum_full_return": float(full.sum()),
        "mean_full_return": float(full.mean()) if len(full) else None,
        "positive_rate": float((full > 0).mean()) if len(full) else None,
        "mean_adverse": float(adverse.mean()) if len(adverse) else None,
        "worst_full": float(full.min()) if len(full) else None,
        "best_full": float(full.max()) if len(full) else None,
    }
    log(f"  UPPER BOUND (sum of standalone-simulated returns, unscaled by notional): "
        f"n={upper_bound['n_blocked_episodes']} sum={upper_bound['sum_full_return']*100:.2f}%(price-move units, NOT account PnL) "
        f"mean={upper_bound['mean_full_return']*100 if upper_bound['mean_full_return'] is not None else float('nan'):.3f}% "
        f"pos_rate={upper_bound['positive_rate']}")

    # context: compare to h48qual's own realized VAL contribution (same units, sum of its trade_return)
    h48_trades = ledger[ledger["source_component"] == "h48qual"]
    h48_sum_return = float(h48_trades["trade_return"].sum())
    zig_trades = ledger[ledger["source_component"] == "zig075"]
    zig_sum_return = float(zig_trades["trade_return"].sum())
    log(f"  context: h48qual's ACTUAL realized VAL sum(trade_return)={h48_sum_return*100:.2f}%  "
        f"zig075's ACTUAL realized VAL sum(trade_return)={zig_sum_return*100:.2f}%  (account-PnL units, notional-scaled -- not directly comparable to the price-move-unit upper bound above, context only)")

    report = {
        "design": "dual-slot candidate cheap_gate -- upper-bound estimate via reused zig075 episode labels, no new simulation engine.",
        "window": WINDOW,
        "fresh_forward_bar_by_bar": True,
        "trade_ledgers_used_as_input": False,
        "saved_parent_exit_timestamps_used": False,
        "future_rows_used_for_entry": False,
        "g0_baseline": baseline_metrics,
        "blocking_breakdown": {"total_episodes": int(len(labels)), "blocked_by_h48qual": int(blocked_h48.sum()), "blocked_by_self": int(blocked_self.sum()), "free": int(free.sum())},
        "upper_bound_estimate": upper_bound,
        "context_actual_realized": {"h48qual_sum_trade_return": h48_sum_return, "zig075_sum_trade_return": zig_sum_return},
        "caveats": [
            "upper bound ignores aggregate NOTIONAL_CAP -- assumes every blocked episode gets full standalone notional",
            "ignores compounding/path effects of adding these trades into the real portfolio equity curve",
            "price-move-unit sum is not directly comparable to account-PnL-unit realized returns without a notional assumption",
        ],
    }
    (OUT_DIR / "report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2, default=omega._json_default) + "\n", encoding="utf-8")
    log(f"report={OUT_DIR / 'report.json'}")
    log("stage=done")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
