#!/usr/bin/env python3
"""RESEARCH ONLY -- ONE-TIME OOS confirmation for the single seed-robustness-confirmed side-finding
from docs/experiments/eth_omega461_live_sltp_wide_calibration_seed_robustness_20260813.md:
symmetric_scale9 (research_eth_omega461_live_sltp_mfe_width_20260813.py's base102 feature panel,
tp_scale=9.0, sl_ratio=sl_mult/tp_mult=0.5 -- the SAME formula/config used in that VAL 5-seed check,
which reproduced 5/5 on no_gate+with_gate pnl+mdd). asymmetric_tp9_sl1.5 was discarded as seed-
variance noise (no_gate MDD only 3/5) and is NOT touched here.

This is the FIRST and (per orchestrator instruction) ONLY OOS look this session takes for this
side-finding. No retuning after seeing the result, no repeat runs with different parameters --
Fresh-Forward discipline (CLAUDE.md) forbids reusing OOS as a second selection round. To minimize
the risk of a code bug silently corrupting this one-time look, this script FIRST re-runs the exact
same pipeline against VAL and asserts it reproduces the already-published VAL 5-seed numbers from
tmp/research_20260813/omega461_live_sltp_wide_calibration_seed_robustness/report.json to a tight
tolerance -- only if that self-check passes does it proceed to the real OOS pass (same code path,
only the split/date-range/prediction-CSV/oof arguments differ, so a passing VAL self-check is strong
evidence the OOS pass is mechanically correct).

MFE regressor TRAIN window is unchanged (2025-01-01..2025-09-30, base102 feature panel) -- OOS is
NEVER mixed into training, only used for scoring + backtest. Same N=5 true-random seeds already used
for the VAL robustness check: [453827194, 121952941, 501601563, 139411872, 13643480].

Reuses, does NOT reimplement:
  - research_eth_omega461_exit_sweep_20260721.py (base_sweep): load_frame, prep_component,
    replay_exit_variant, OOS_START/OOS_END (2026-01-01..2026-03-31, this script's OWN standard OOS
    window, used unmodified).
  - research_eth_omega461_live_sltp_mfe_width_20260813.py (mfe_width): base102_panel,
    train_mfe_models, predicted_width, apply_mfe_width_sltp, _ledger_stats, _duration_gated,
    _as_router_component, _load_tb_labels, FLOOR_TP/FLOOR_SL/TRAIN_START/TRAIN_END/MFE_MODEL_SEED.
  - replay_omega4_6_1_greedy_router_20260706.py (router): greedy_replay.

fresh_forward_bar_by_bar=true. trade_ledgers_used_as_input=false.
saved_parent_exit_timestamps_used=false. future_rows_used_for_entry=false.
Does NOT touch trading_bot_modules/omega4_6_1_live.py, trading_bot.py, runtime_config.py, .env.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import torch

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
if str(ROOT / "scripts") not in sys.path:
    sys.path.insert(0, str(ROOT / "scripts"))

import replay_omega4_6_1_greedy_router_20260706 as router  # noqa: E402
import research_eth_omega461_live_sltp_mfe_width_20260813 as mfe_width  # noqa: E402

base_sweep = mfe_width.base_sweep

OUT_DIR = ROOT / "tmp/research_20260813/omega461_live_sltp_wide_calibration_oos_confirm"
SEEDS = [453827194, 121952941, 501601563, 139411872, 13643480]  # identical to the VAL robustness check
PRIOR_REPORT = ROOT / "tmp/research_20260813/omega461_live_sltp_wide_calibration_seed_robustness/report.json"
TP_SCALE = 9.0


def log(msg: str) -> None:
    print(msg, flush=True)


def _ffill_regime3_gap(frame: pd.DataFrame, split_label: str) -> pd.DataFrame:
    """Harness-only data-hygiene patch, NOT a mechanism change. The live WIDE24_2026 overlay CSV
    (regenerated by other concurrent work in this shared repo since research_eth_omega461_exit_
    sweep_20260721.py's own OOS run on 2026-07-21 -- same pattern already documented in
    research_eth_omega461_tpsl_floor_portfolio_check_20260728.py's _truncated_pred_csv comment)
    currently has a genuine, contiguous ~8h gap (95/25,633 OOS rows, 2026-02-28 16:05..23:55) in the
    6 regime3_current_sensitive_wide24_* columns. hard._route_id() raises on any non-finite value in
    its 3 route-probability columns (no tolerance), which would otherwise crash EVERY script that
    calls it on today's OOS frame -- including the unmodified research_eth_omega461_exit_sweep_
    20260721.replay_exit_variant, not something specific to this script. parent._base_input already
    silently zero-fills these same columns for entry-decision scoring elsewhere in the pipeline; a
    hard zero for a probability-family column is a worse causal approximation than carrying forward
    the last known classification, so this forward-fills ALL 6 regime3_current_sensitive_wide24_*
    columns (not just the 3 route cols hard._route_id checks) for internal consistency, using ONLY
    already-elapsed data (strictly causal). Applied identically before baseline and the MFE-width
    candidate branch off, so both see the exact same patched frame -- does not touch direction/
    quality/entry-timing logic, only patches a missing INPUT for 0.37% of rows. Verified below that
    no non-finite values remain after the fill."""
    cols = [c for c in frame.columns if c.startswith("regime3_current_sensitive_wide24_")]
    n_before = int(frame[cols].isna().any(axis=1).sum())
    if n_before == 0:
        return frame
    out = frame.copy()
    out[cols] = out[cols].ffill()
    n_after = int(out[cols].isna().any(axis=1).sum())
    log(f"  [{split_label}] regime3 overlay gap patch: {n_before} rows had NaN in {cols}, forward-filled, {n_after} remaining NaN after fill")
    if n_after:
        raise RuntimeError(f"{split_label}: {n_after} rows still non-finite in regime3 columns after ffill (gap at series start?) -- refusing to silently proceed")
    return out


def run_split(*, split_label: str, start: str, end: str, base_csv: Path, wide24_csv: Path, pred_prefix: str, oof: bool,
              base_cols: list[str], panel_train: pd.DataFrame, feat_cols: list[str], train_labels: pd.DataFrame) -> dict[str, Any]:
    frame = base_sweep.load_frame(start, end, base_csv=base_csv, wide24_csv=wide24_csv)
    frame = _ffill_regime3_gap(frame, split_label)
    log(f"  [{split_label}] frame rows={len(frame)} range=[{frame['timestamp'].min()}, {frame['timestamp'].max()}]")

    prepped: dict[str, dict[str, Any]] = {}
    for name, cfg in base_sweep.COMPONENTS.items():
        pred_csv = base_sweep.EXT_PRED_DIR / name / f"{pred_prefix}_predictions_{cfg['q_tag']}.csv"
        prepped[name] = base_sweep.prep_component(name, cfg, frame, pred_csv, oof=oof)

    router_base = {name: mfe_width._as_router_component(p, exit_threshold=base_sweep.BASELINE_EXIT_THRESHOLD) for name, p in prepped.items()}
    fee0, slip0 = prepped["h48qual"]["fee"], prepped["h48qual"]["slip"]
    _, ledger_base = router.greedy_replay(frame, router_base, fee=fee0, slip=slip0, cost_mult=base_sweep.COST_MULT, device=base_sweep.DEVICE)
    baseline = {"no_gate": mfe_width._ledger_stats(ledger_base, frame), "with_gate": mfe_width._duration_gated(ledger_base, frame, router.DURATION_THRESHOLD)}
    log(f"  [{split_label}] baseline no_gate pnl={baseline['no_gate']['pnl']:.2f} mdd={baseline['no_gate']['mdd']:.2f} trades={baseline['no_gate']['trades']}")

    panel_split, _ = mfe_width.base102_panel(base_cols, frame)
    x_scoring = panel_split[feat_cols]

    seed_results = []
    for seed in SEEDS:
        models, _train_diag = mfe_width.train_mfe_models(panel_train, feat_cols, train_labels, seed=seed)  # TRAIN window unchanged regardless of split
        widths = {}
        for name, p in prepped.items():
            side = pd.to_numeric(p["dec"]["side"], errors="raise").to_numpy(dtype=np.int64)
            widths[name] = mfe_width.predicted_width(models, x_scoring, side)
        comps = {}
        for name, p in prepped.items():
            cfg = base_sweep.COMPONENTS[name]
            sl_ratio = float(cfg["sl_mult"]) / float(cfg["tp_mult"])
            dec_sym, _ = mfe_width.apply_mfe_width_sltp(p["dec"], widths[name], tp_scale=TP_SCALE, sl_ratio=sl_ratio,
                                                          min_tp=mfe_width.FLOOR_TP, min_sl=mfe_width.FLOOR_SL, max_tp=cfg["max_tp"], max_sl=cfg["max_sl"])
            comps[name] = {**router_base[name], "dec": dec_sym}
        _, ledger = router.greedy_replay(frame, comps, fee=fee0, slip=slip0, cost_mult=base_sweep.COST_MULT, device=base_sweep.DEVICE)
        res = {"no_gate": mfe_width._ledger_stats(ledger, frame), "with_gate": mfe_width._duration_gated(ledger, frame, router.DURATION_THRESHOLD)}
        seed_results.append({"seed": seed, **res})
        log(f"    seed={seed} no_gate pnl={res['no_gate']['pnl']:.2f} mdd={res['no_gate']['mdd']:.2f} trades={res['no_gate']['trades']} "
            f"| with_gate pnl={res['with_gate']['pnl']:.2f} mdd={res['with_gate']['mdd']:.2f}")
        ledger.to_csv(OUT_DIR / f"ledger_{split_label}_symmetric_scale9_seed{seed}.csv", index=False)

    return {"baseline": baseline, "seed_results": seed_results}


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    bundle_h48 = torch.load(base_sweep.COMPONENTS["h48qual"]["bundle"], map_location="cpu", weights_only=False)
    base_cols = list(bundle_h48["base_cols"])
    train_frame = base_sweep.load_frame(mfe_width.TRAIN_START, mfe_width.TRAIN_END, base_csv=base_sweep.BASE_2025, wide24_csv=base_sweep.WIDE24_2025)
    panel_train, feat_cols = mfe_width.base102_panel(base_cols, train_frame)
    train_labels = mfe_width._load_tb_labels("train")

    # --- Step 1: self-check against the already-published VAL 5-seed result before ever touching OOS ---
    log("stage=self_check_VAL (verifying this script's pipeline reproduces the already-published VAL numbers before touching OOS)")
    val_result = run_split(split_label="VAL_selfcheck", start=base_sweep.VAL_START, end=base_sweep.VAL_END,
                            base_csv=base_sweep.BASE_2025, wide24_csv=base_sweep.WIDE24_2025, pred_prefix="validation", oof=True,
                            base_cols=base_cols, panel_train=panel_train, feat_cols=feat_cols, train_labels=train_labels)

    prior = json.loads(PRIOR_REPORT.read_text())
    prior_seed_results = prior["per_seed_results"]
    mismatches = []
    for got, prior_r in zip(val_result["seed_results"], prior_seed_results):
        assert got["seed"] == prior_r["seed"], f"seed order mismatch: {got['seed']} vs {prior_r['seed']}"
        prior_sym = prior_r["results"]["symmetric_scale9"]
        for gate in ("no_gate", "with_gate"):
            for metric in ("pnl", "mdd", "trades"):
                a, b = got[gate][metric], prior_sym[gate][metric]
                if abs(float(a) - float(b)) > 1.0e-6 * max(1.0, abs(float(b))):
                    mismatches.append(f"seed={got['seed']} {gate}.{metric}: self_check={a} prior_published={b}")
    if mismatches:
        log("SELF-CHECK FAILED -- mismatches vs the already-published VAL result:")
        for m in mismatches:
            log(f"  {m}")
        raise RuntimeError("VAL self-check did not reproduce the published seed-robustness result -- refusing to spend the one-time OOS look until this is fixed")
    log("stage=self_check_VAL PASSED -- pipeline reproduces the published VAL 5-seed numbers exactly. Proceeding to the ONE-TIME OOS pass.")

    # --- Step 2: the one, real OOS pass ---
    log(f"stage=OOS_confirm (ONE TIME ONLY) window=[{base_sweep.OOS_START}, {base_sweep.OOS_END}]")
    oos_result = run_split(split_label="OOS", start=base_sweep.OOS_START, end=base_sweep.OOS_END,
                            base_csv=base_sweep.BASE_2026, wide24_csv=base_sweep.WIDE24_2026, pred_prefix="oos", oof=False,
                            base_cols=base_cols, panel_train=panel_train, feat_cols=feat_cols, train_labels=train_labels)

    report = {
        "model_id": "omega461_live_sltp_wide_calibration_oos_confirm_20260813",
        "parent_experiments": [
            "docs/experiments/eth_omega461_live_sltp_mfe_width_20260813.md",
            "docs/experiments/eth_omega461_live_sltp_wide_calibration_seed_robustness_20260813.md",
        ],
        "config": "symmetric_scale9 (base102, tp_scale=9.0, sl_ratio=0.5) ONLY -- asymmetric_tp9_sl1.5 discarded, not tested here",
        "seeds": SEEDS, "oos_window": [base_sweep.OOS_START, base_sweep.OOS_END],
        "val_self_check_passed": True,
        "val_self_check_result": val_result, "oos_result": oos_result,
        "fresh_forward_bar_by_bar": True, "trade_ledgers_used_as_input": False,
        "saved_parent_exit_timestamps_used": False, "future_rows_used_for_entry": False,
        "one_time_oos_look": True, "oos_reused_after_seeing_result": False,
    }
    (OUT_DIR / "report.json").write_text(json.dumps(report, indent=2, ensure_ascii=False, default=base_sweep.omega._json_default), encoding="utf-8")

    log("\n=== VAL vs OOS, symmetric_scale9, 5 seeds ===")
    rows = []
    for split_label, result in (("VAL", val_result), ("OOS", oos_result)):
        rows.append({"split": split_label, "seed": "baseline", **{f"no_gate_{k}": v for k, v in result["baseline"]["no_gate"].items() if k in ("pnl", "mdd", "trades", "avg_hold_bars")},
                      **{f"with_gate_{k}": v for k, v in result["baseline"]["with_gate"].items() if k in ("pnl", "mdd", "trades")}})
        for sr in result["seed_results"]:
            rows.append({"split": split_label, "seed": sr["seed"], **{f"no_gate_{k}": v for k, v in sr["no_gate"].items() if k in ("pnl", "mdd", "trades", "avg_hold_bars")},
                         **{f"with_gate_{k}": v for k, v in sr["with_gate"].items() if k in ("pnl", "mdd", "trades")}})
    cmp_df = pd.DataFrame(rows)
    cmp_df.to_csv(OUT_DIR / "val_vs_oos_comparison.csv", index=False)
    log(cmp_df.to_string(index=False))

    log(f"\nstage=done report={OUT_DIR / 'report.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
