#!/usr/bin/env python3
"""Research-only distributional optimal stopping follow-up for ETH Omega4.6.1.

The earlier mean return-to-go experiment overfit.  This version predicts q10/q50/q90 of the
terminal price move under the frozen SLTP continuation policy and grants an early exit only when
the current liquidation value exceeds the conservative q90 continuation estimate by a margin.

It reuses the post-quality non-overlapping episode datasets generated by
research_eth_omega461_competing_risk_rescue_20260724.py.  Selection is made on VAL against the
already-selected competing-risk winner.  OOS is loaded only if a distributional configuration
beats that winner under the predeclared VAL gate.
"""

from __future__ import annotations

import json
import pickle
import sys
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.metrics import mean_pinball_loss


ROOT = Path(__file__).resolve().parents[1]
for path in (ROOT, ROOT / "scripts"):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

import research_eth_omega461_competing_risk_rescue_20260724 as hazard  # noqa: E402
import research_eth_omega461_exit_sweep_20260721 as sweep  # noqa: E402


MODEL_ID = "eth_omega461_distributional_stopping_20260724"
OUT_DIR = ROOT / "tmp/causal_regen_20260516" / MODEL_ID
QUANTILES = {"q10": 0.10, "q50": 0.50, "q90": 0.90}
SEED = 260725


def _json_default(value: Any) -> Any:
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (np.floating,)):
        return float(value)
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, Path):
        return str(value)
    raise TypeError(type(value).__name__)


def fit_distributional_bundle(data: pd.DataFrame, *, seed: int) -> tuple[dict[str, Any], dict[str, Any]]:
    feature_cols = hazard._feature_columns(data)
    x = data[feature_cols].to_numpy(dtype=np.float64)
    y = data["terminal_move"].to_numpy(dtype=np.float64)
    weights = data["sample_weight"].to_numpy(dtype=np.float64)
    timestamps = pd.to_datetime(data["entry_timestamp"], errors="raise")
    split_ts = timestamps.quantile(0.80)
    train_mask = timestamps <= split_ts
    diag_mask = timestamps > split_ts
    if int(train_mask.sum()) == 0 or int(diag_mask.sum()) == 0:
        raise RuntimeError("distributional internal time split is empty")

    models: dict[str, HistGradientBoostingRegressor] = {}
    diagnostics: dict[str, Any] = {"split_timestamp": str(split_ts), "train_rows": int(train_mask.sum()), "diag_rows": int(diag_mask.sum())}
    for offset, (name, quantile) in enumerate(QUANTILES.items()):
        diagnostic_model = HistGradientBoostingRegressor(
            loss="quantile",
            quantile=float(quantile),
            learning_rate=0.05,
            max_iter=140,
            max_leaf_nodes=15,
            min_samples_leaf=40,
            l2_regularization=1.0,
            early_stopping=False,
            random_state=int(seed + offset),
        )
        diagnostic_model.fit(x[train_mask], y[train_mask], sample_weight=weights[train_mask])
        pred = diagnostic_model.predict(x[diag_mask])
        diagnostics[name] = {
            "pinball_loss": float(mean_pinball_loss(y[diag_mask], pred, alpha=float(quantile), sample_weight=weights[diag_mask])),
            "empirical_coverage": float(np.average(y[diag_mask] <= pred, weights=weights[diag_mask])),
            "prediction_quantiles": {
                str(q): float(np.quantile(pred, q)) for q in (0.10, 0.50, 0.90)
            },
        }
        final_model = HistGradientBoostingRegressor(
            loss="quantile",
            quantile=float(quantile),
            learning_rate=0.05,
            max_iter=140,
            max_leaf_nodes=15,
            min_samples_leaf=40,
            l2_regularization=1.0,
            early_stopping=False,
            random_state=int(seed + 100 + offset),
        )
        final_model.fit(x, y, sample_weight=weights)
        models[name] = final_model
    return (
        {
            "kind": "distributional_continuation",
            "models": models,
            "feature_columns": feature_cols,
            "quantiles": QUANTILES,
            "label": "terminal_price_move_under_frozen_sltp",
        },
        diagnostics,
    )


def clears_hazard(candidate: dict[str, Any], hazard_winner: dict[str, Any]) -> bool:
    return bool(
        candidate["log_risk_utility"] > hazard_winner["log_risk_utility"]
        and candidate["pnl"] >= 0.90 * hazard_winner["pnl"]
        and candidate["mdd"] >= hazard_winner["mdd"]
        and candidate["rescue_counterfactual_causes"].get("take_profit", 0)
        <= candidate["rescue_counterfactual_causes"].get("stop_loss", 0)
    )


def load_components(frame: pd.DataFrame, *, split: str, oof: bool) -> dict[str, dict[str, Any]]:
    out: dict[str, dict[str, Any]] = {}
    for name, cfg in sweep.COMPONENTS.items():
        out[name] = hazard.prepare_split(
            name,
            cfg,
            frame,
            hazard._prediction_path(split, name, cfg),
            oof=oof,
            pre_quality=False,
        )
    return out


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    hazard_report_path = hazard.OUT_DIR / "report.json"
    if not hazard_report_path.exists():
        raise FileNotFoundError(f"run competing-risk stage first: {hazard_report_path}")
    hazard_report = json.loads(hazard_report_path.read_text(encoding="utf-8"))
    if not bool(hazard_report.get("oos_pass")):
        raise RuntimeError("competing-risk stage did not pass OOS; distributional follow-up is gated off")
    hazard_winner = dict(hazard_report["selected"])

    bundles: dict[str, dict[str, Any]] = {}
    diagnostics: dict[str, Any] = {}
    for idx, name in enumerate(sweep.COMPONENTS):
        dataset_path = hazard.OUT_DIR / f"train_dataset_{name}_B_post_quality.csv.gz"
        print(f"stage=load_dataset component={name} path={dataset_path}", flush=True)
        data = pd.read_csv(dataset_path, low_memory=False)
        print(f"stage=fit_quantiles component={name} rows={len(data)} episodes={data['episode_id'].nunique()}", flush=True)
        bundle, diag = fit_distributional_bundle(data, seed=SEED + idx * 10)
        bundles[name] = bundle
        diagnostics[name] = diag
        with open(OUT_DIR / f"distributional_bundle_{name}.pkl", "wb") as handle:
            pickle.dump(bundle, handle)
    (OUT_DIR / "fit_diagnostics.json").write_text(
        json.dumps(diagnostics, indent=2, ensure_ascii=False, default=_json_default), encoding="utf-8"
    )

    val_frame = sweep.load_frame(sweep.VAL_START, sweep.VAL_END, base_csv=sweep.BASE_2025, wide24_csv=sweep.WIDE24_2025)
    val_components = load_components(val_frame, split="validation", oof=True)
    rows: list[dict[str, Any]] = []
    winners: list[dict[str, Any]] = []
    for value_margin in (0.0, 0.0025, 0.0050, 0.0100):
        for persistence in (1, 3):
            print(f"stage=val margin={value_margin} persistence={persistence}", flush=True)
            metrics, ledger = hazard.replay_router(
                val_frame,
                val_components,
                rescue_bundles=bundles,
                sl_probability_min=0.0,
                value_margin=value_margin,
                persistence=persistence,
            )
            clears = clears_hazard(metrics, hazard_winner)
            row = {"value_margin": value_margin, "persistence": persistence, **metrics, "clears_hazard_val": clears}
            rows.append(row)
            if clears:
                winners.append(row)
                ledger.to_csv(OUT_DIR / f"validation_ledger_m{value_margin:.4f}_p{persistence}.csv", index=False)
    ranking = pd.DataFrame(rows).sort_values(
        ["clears_hazard_val", "log_risk_utility", "mdd", "pnl"], ascending=[False, False, False, False]
    )
    ranking.to_csv(OUT_DIR / "validation_ranking.csv", index=False)
    selected = max(winners, key=lambda row: (row["log_risk_utility"], row["mdd"], row["pnl"])) if winners else None
    report: dict[str, Any] = {
        "model_id": MODEL_ID,
        "status": "val_rejected" if selected is None else "val_selected_oos_pending",
        "competing_risk_reference": hazard_winner,
        "fit_diagnostics": diagnostics,
        "selected": selected,
        "protocol": {
            "train_source": "post-quality non-overlapping episode datasets from competing-risk stage",
            "validation": [sweep.VAL_START, sweep.VAL_END],
            "oos": [sweep.OOS_START, sweep.OOS_END],
            "fresh_forward_bar_by_bar": True,
            "trade_ledgers_used_as_input": False,
            "saved_parent_exit_timestamps_used": False,
            "future_rows_used_for_entry": False,
            "training_future_rows_used_for_labels_only": True,
            "decision_rule": "exit_now >= predicted_q90_continuation + margin",
        },
    }
    if selected is None:
        (OUT_DIR / "report.json").write_text(
            json.dumps(report, indent=2, ensure_ascii=False, default=_json_default), encoding="utf-8"
        )
        print("stage=done no_val_winner; OOS not opened", flush=True)
        return 0

    print(f"stage=oos_confirm selected={selected}", flush=True)
    oos_frame = sweep.load_frame(sweep.OOS_START, sweep.OOS_END, base_csv=sweep.BASE_2026, wide24_csv=sweep.WIDE24_2026)
    oos_components = load_components(oos_frame, split="oos", oof=False)
    oos_metrics, oos_ledger = hazard.replay_router(
        oos_frame,
        oos_components,
        rescue_bundles=bundles,
        sl_probability_min=0.0,
        value_margin=float(selected["value_margin"]),
        persistence=int(selected["persistence"]),
    )
    oos_ledger.to_csv(OUT_DIR / "oos_ledger_selected.csv", index=False)
    hazard_oos = dict(hazard_report["oos_candidate"])
    report["status"] = "oos_confirmed"
    report["oos_competing_risk_reference"] = hazard_oos
    report["oos_candidate"] = oos_metrics
    report["oos_pass"] = clears_hazard(oos_metrics, hazard_oos)
    (OUT_DIR / "report.json").write_text(
        json.dumps(report, indent=2, ensure_ascii=False, default=_json_default), encoding="utf-8"
    )
    print(json.dumps({"report": str(OUT_DIR / "report.json"), "selected": selected, "oos_pass": report["oos_pass"]}, indent=2, default=_json_default), flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
