#!/usr/bin/env python3
"""Meta-labeling (Lopez de Prado) on the Sigma3 1h primary, to raise entry win-rate and push
cost3 over the line without changing the (working) 1h primary signal.

Pipeline:
1. Primary = 5-seed HGB ensemble on 1h trend-scanning labels (Sigma3, unchanged), proba over all bars.
2. Over the TRAINING period (2024-01..2025-06), for every bar where the primary would enter
   (argmax is LONG/SHORT and its prob >= base 0.5), simulate the forward trade with the frozen
   barriers (tp1.5/sl1.0 x ATR, max_hold 48, cooldown ignored for labeling) and label win=1 if
   the net-of-cost1 return is positive, else 0.
3. Meta-model = HGB binary classifier on the 38 MARKET features (NOT primary proba, to avoid
   primary-overfit leakage) -> P(this primary signal wins).
4. Emit a tape where an entry is kept only if meta P(win) >= meta_threshold; sweep meta_threshold.
   Validate on 2025-07..12.

Note on leakage: meta trade-outcome labels on the training period were generated by the primary
that trained on that period, so the primary is mildly overfit there. This can only inflate the
IN-SAMPLE meta fit, not the OUT-OF-SAMPLE validation -- so a real improvement on 2025-07..12 is
meaningful. Validation-only here; one-shot handled separately, once, with the 2nd-use caveat.
"""

from __future__ import annotations

import itertools
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.ensemble import HistGradientBoostingClassifier

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
if str(ROOT / "scripts") not in sys.path:
    sys.path.insert(0, str(ROOT / "scripts"))

import replay_omega6_v2_variants_20260704 as v2  # noqa: E402

DATA_DIR = ROOT / "tmp/causal_regen_20260516/sigma3_1h_trendscan_20260705"
OUT_DIR = ROOT / "tmp/causal_regen_20260516/sigma3_metalabel_20260705"
TRAIN_END = pd.Timestamp("2025-06-30 23:59:59")
TAPE_START = pd.Timestamp("2025-06-25")
VAL_START = pd.Timestamp("2025-07-01")
VAL_END = pd.Timestamp("2025-12-31 23:59:59")
SEEDS = [270705, 270710, 270715, 270720, 270725]
NON_FEATURE = {"timestamp", "open", "high", "low", "close", "ts_action", "ts_t_value", "ts_opt_L"}
TP_MULT, SL_MULT, MAX_HOLD = 1.5, 1.0, 48
FEE, SLIP = 0.00020, 0.00050
NOTIONAL = 0.6


def load_all() -> pd.DataFrame:
    frames = [pd.read_parquet(DATA_DIR / f"sigma3_1h_{y}.parquet") for y in (2024, 2025, 2026)]
    df = pd.concat(frames, ignore_index=True)
    df["timestamp"] = pd.to_datetime(df["timestamp"])
    return df.sort_values("timestamp").drop_duplicates("timestamp").reset_index(drop=True)


def ensemble_proba(X_tr, y_tr, w, X_all) -> np.ndarray:
    ps = np.zeros((len(X_all), 3))
    for s in SEEDS:
        clf = HistGradientBoostingClassifier(loss="log_loss", learning_rate=0.03, max_iter=250,
                                             max_depth=4, l2_regularization=1.0, max_leaf_nodes=31,
                                             min_samples_leaf=80, early_stopping=False,
                                             random_state=int(s), class_weight="balanced")
        clf.fit(X_tr, y_tr, sample_weight=w)
        pr = clf.predict_proba(X_all)
        cm = {c: i for i, c in enumerate(list(clf.classes_))}
        for k in (0, 1, 2):
            if k in cm:
                ps[:, k] += pr[:, cm[k]]
    return ps / len(SEEDS)


def simulate_trade_net(close, open_, atr, i, side, n) -> float:
    """cost1 net return of a trade entered at bar i (fill next open), frozen barriers."""
    entry = open_[min(i + 1, n - 1)] * (1 + SLIP if side > 0 else 1 - SLIP)
    tp, sl = TP_MULT * atr[i], SL_MULT * atr[i]
    for j in range(i + 1, min(i + 1 + MAX_HOLD, n)):
        px = close[j]
        raw = (px * (1 - SLIP) - entry) / entry if side > 0 else (entry - px * (1 + SLIP)) / entry
        unreal = raw * NOTIONAL
        if unreal >= tp or unreal <= -sl:
            return unreal - FEE * NOTIONAL * 2
    j = min(i + MAX_HOLD, n - 1)
    px = close[j]
    raw = (px * (1 - SLIP) - entry) / entry if side > 0 else (entry - px * (1 + SLIP)) / entry
    return raw * NOTIONAL - FEE * NOTIONAL * 2


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    df = load_all()
    feat_cols = [c for c in df.columns if c not in NON_FEATURE]
    ts = df["timestamp"]
    train_mask = (ts <= TRAIN_END).to_numpy()
    Xtr = df.loc[train_mask, feat_cols].to_numpy(dtype=np.float64)
    ytr = df.loc[train_mask, "ts_action"].to_numpy(dtype=np.int64)
    w = np.clip(np.abs(df.loc[train_mask, "ts_t_value"].to_numpy(dtype=np.float64)), 0.5, 12.0)
    Xall = df[feat_cols].to_numpy(dtype=np.float64)

    proba = ensemble_proba(Xtr, ytr, w, Xall)
    da = proba.argmax(axis=1)
    prim_side = np.where(da == 1, 1, np.where(da == 2, -1, 0))
    prim_conf = np.where(da > 0, proba[np.arange(len(df)), da], 0.0)

    close = df["close"].to_numpy(dtype=np.float64)
    open_ = df["open"].to_numpy(dtype=np.float64)
    atr = df["atr_pct"].to_numpy(dtype=np.float64)
    n = len(df)

    # meta training samples: training-period bars where primary would enter at base thr 0.5
    entry_mask = train_mask & (prim_side != 0) & (prim_conf >= 0.5)
    entry_idx = np.flatnonzero(entry_mask)
    entry_idx = entry_idx[entry_idx < n - 2]
    meta_y = np.array([1 if simulate_trade_net(close, open_, atr, i, int(prim_side[i]), n) > 0 else 0 for i in entry_idx], dtype=np.int64)
    print(f"meta train entries: {len(entry_idx)}, win rate: {meta_y.mean():.3f}", flush=True)

    meta_X = Xall[entry_idx]
    meta = HistGradientBoostingClassifier(loss="log_loss", learning_rate=0.03, max_iter=300,
                                          max_depth=4, l2_regularization=1.0, max_leaf_nodes=31,
                                          min_samples_leaf=50, early_stopping=False,
                                          random_state=99, class_weight="balanced")
    meta.fit(meta_X, meta_y)
    win_col = list(meta.classes_).index(1)
    meta_pwin = meta.predict_proba(Xall)[:, win_col]

    # base tape from 2025-06-25, with primary side/conf; meta filter applied per-threshold below
    tape_mask = (ts >= TAPE_START).to_numpy()
    sub = df.loc[tape_mask].reset_index(drop=True)
    base = {
        "i": np.arange(len(sub)), "timestamp": sub["timestamp"],
        "open": sub["open"].astype(float), "high": sub["high"].astype(float),
        "low": sub["low"].astype(float), "close": sub["close"].astype(float),
        "jump_flag": 0.0, "evt_tail_flag": 0.0, "jump_z": 0.0, "atr_pct": sub["atr_pct"].astype(float),
        "primary_expert": "sigma3meta", "primary_route_confidence": 1.0, "primary_route_margin": 1.0,
        "fallback_action": 0, "fallback_side": 0, "fallback_expert": "none",
        "fallback_route_confidence": 0.0, "fallback_route_margin": 0.0,
        "fallback_dir_p_cash": 1.0, "fallback_dir_p_long": 0.0, "fallback_dir_p_short": 0.0,
        "fallback_quality_p_cash": 1.0, "fallback_quality_p_long": 0.0, "fallback_quality_p_short": 0.0,
        "fallback_quality_score": 0.0, "fallback_confidence": 0.0,
    }
    pc, pl, psh = proba[tape_mask, 0], proba[tape_mask, 1], proba[tape_mask, 2]
    mp = meta_pwin[tape_mask]

    rows = []
    # grid: base primary threshold (keep low, rely on meta) x meta threshold x (tp,sl) x persistence
    for base_thr, meta_thr, per in itertools.product([0.45, 0.50], [0.50, 0.55, 0.60, 0.65], [0, 2]):
        P = np.column_stack([pc, pl, psh])
        da2 = P.argmax(axis=1)
        conf = np.where(da2 > 0, P[np.arange(len(sub)), da2], 0.0)
        keep = (da2 != 0) & (conf >= base_thr) & (mp >= meta_thr)
        fa = np.where(keep, da2, 0)
        side = np.where(fa == 1, 1, np.where(fa == 2, -1, 0))
        tape = pd.DataFrame({**base,
            "primary_action": fa, "primary_side": side,
            "primary_dir_p_cash": pc, "primary_dir_p_long": pl, "primary_dir_p_short": psh,
            "primary_quality_p_cash": pc, "primary_quality_p_long": pl, "primary_quality_p_short": psh,
            "primary_quality_score": np.where(fa != 0, conf, 0.0), "primary_confidence": P.max(axis=1)})
        # run_variant will re-derive side from primary_side via apply_quality_threshold; to keep the
        # meta filter, DON'T re-threshold -- call cost_stress on this tape directly with quality_threshold=0
        cfg = v2.VariantConfig(name=f"meta_b{base_thr}_m{meta_thr}_p{per}", tp_mode="atr_scaled",
                               tp_atr_mult=TP_MULT, sl_atr_mult=SL_MULT, sizing_mode="fixed",
                               fixed_margin=0.30, fixed_leverage=2.0, cooldown_bars=3,
                               quality_threshold=0.0, persistence_bars=per, max_hold_bars=MAX_HOLD, use_fallback=False)
        r = v2.cost_stress(tape, cfg, start=VAL_START, end=VAL_END)
        c1, c3 = r["cost1"], r["cost3"]
        gate = c1["pnl"] > 0 and c3["pnl"] > 0 and c1["mdd"] >= -20 and c3["mdd"] >= -20 and c1["trades"] >= 40 and len(c1["trades_by_month"]) >= 5
        rows.append({"base_thr": base_thr, "meta_thr": meta_thr, "per": per,
                     "c1": round(c1["pnl"], 2), "c1mdd": round(c1["mdd"], 2), "c1tr": c1["trades"], "c1wr": round(c1["wr"], 3),
                     "c3": round(c3["pnl"], 2), "c3mdd": round(c3["mdd"], 2), "mo": len(c1["trades_by_month"]), "pass": gate})
    rdf = pd.DataFrame(rows).sort_values(["pass", "c3"], ascending=[False, False])
    rdf.to_csv(OUT_DIR / "metalabel_gate_ranking.csv", index=False)
    # save proba+meta for a possible one-shot
    np.savez(OUT_DIR / "signals.npz", proba=proba, meta_pwin=meta_pwin, timestamp=ts.astype("int64").to_numpy())
    print(f"\nmeta gate_pass: {int(rdf['pass'].sum())}/{len(rdf)}", flush=True)
    print(rdf.to_string(index=False), flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
