#!/usr/bin/env python3
"""Train the 2-action portfolio RL gate in the native bar-by-bar environment.

This replaces the earlier event-ledger-trained policy with a validation-only
native policy. Training uses transitions generated by a validation native
rule_take_all replay, not saved trade ledgers. OOS is evaluated once after
policy training.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

import replay_portfolio_rl_gate_2action_native_20260708 as native
import train_portfolio_rl_gate_2action_20260708 as proto

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "tmp/causal_regen_20260516/portfolio_rl_gate_2action_native_train_20260709"
DOC_PATH = ROOT / "docs/model_contracts/portfolio_rl_gate_2action_native_train_20260709.md"


def _json_default(obj: Any) -> Any:
    if isinstance(obj, (np.integer,)):
        return int(obj)
    if isinstance(obj, (np.floating,)):
        return float(obj)
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    if isinstance(obj, pd.Timestamp):
        return obj.isoformat()
    if isinstance(obj, Path):
        return str(obj)
    raise TypeError(type(obj).__name__)


def _fit_ridge(x: np.ndarray, y: np.ndarray, l2: float) -> np.ndarray:
    xtx = x.T @ x
    penalty = np.eye(xtx.shape[0]) * float(l2)
    penalty[0, 0] = 0.0
    return np.linalg.solve(xtx + penalty, x.T @ y)


def _feature_row(world: dict[str, Any], c: native.Candidate) -> pd.DataFrame:
    ts = c.timestamp
    row = {
        "is_eth": float(c.asset == "eth"),
        "is_sol": float(c.asset == "sol"),
        "is_btc": float(c.asset == "btc"),
        "is_long": float(c.side > 0),
        "is_short": float(c.side < 0),
        "notional": float(c.notional),
        "margin_fraction": float(c.margin),
        "leverage": float(c.leverage),
        "ou_halflife": float(world[c.asset]["frame"]["ou_halflife"].iloc[c.local_i]),
        "asset_score": float(native.ASSET_SCORES[c.asset]),
        # Native training intentionally starts without realized-return lags:
        # they depend on the learned policy's selected-trade path.
        "ret_lag1_asset": 0.0,
        "ret_lag3_asset": 0.0,
        "hour": float(ts.hour),
        "month": float(ts.month),
    }
    return pd.DataFrame([row], columns=proto.FEATURE_COLS)


def _build_transitions_from_native_rule_ledger(world: dict[str, Any], ledger: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    event_times = pd.to_datetime(ledger["entry_timestamp"]).to_numpy(dtype="datetime64[ns]")
    for event_i, row in ledger.reset_index(drop=True).iterrows():
        asset = str(row["asset"])
        ts = pd.Timestamp(row["entry_timestamp"])
        c = native.Candidate(
            asset=asset,
            component=str(row["component"]),
            local_i=int(row["entry_signal_i"]),
            timestamp=ts,
            side=int(row["side"]),
            margin=float(row["margin_fraction"]),
            leverage=float(row["leverage"]),
            notional=float(row["notional"]),
            take_profit=float(row.get("take_profit", 0.0) or 0.0),
            stop_loss=float(row.get("stop_loss", 0.0) or 0.0),
        )
        feat = _feature_row(world, c).iloc[0].to_dict()
        exit_ts = pd.Timestamp(row["exit_timestamp"])
        rows.append(
            {
                "event_i": int(event_i),
                "timestamp": ts,
                "asset": asset,
                "component": str(row["component"]),
                "side": int(row["side"]),
                "reward_take_raw": float(row["trade_return"]),
                "exit_timestamp": exit_ts,
                "next_skip": min(int(event_i) + 1, len(ledger)),
                "next_take": int(np.searchsorted(event_times, np.datetime64(exit_ts), side="right")),
                **feat,
            }
        )
    return pd.DataFrame(rows)


def _design_matrix(events: pd.DataFrame, action: int) -> np.ndarray:
    return proto._design_matrix(events[proto.FEATURE_COLS], action)


def _train_native_fqi(events: pd.DataFrame, *, gamma: float = 0.97, l2: float = 1.0, iterations: int = 50) -> proto.QPolicy:
    n = len(events)
    reward_skip = np.zeros(n, dtype=np.float64)
    raw_take = events["reward_take_raw"].to_numpy(dtype=np.float64)
    notional = events["notional"].to_numpy(dtype=np.float64)
    tail_penalty = np.maximum(0.0, -raw_take - 0.03)
    reward_take = raw_take - 0.50 * tail_penalty - 0.005 * notional
    next_skip = events["next_skip"].to_numpy(dtype=np.int64)
    next_take = events["next_take"].to_numpy(dtype=np.int64)
    x = np.vstack([_design_matrix(events, 0), _design_matrix(events, 1)])
    weights = np.zeros(x.shape[1], dtype=np.float64)
    for _ in range(int(iterations)):
        q0 = _design_matrix(events, 0) @ weights
        q1 = _design_matrix(events, 1) @ weights
        vmax = np.maximum(q0, q1)
        cont_skip = np.zeros(n, dtype=np.float64)
        cont_take = np.zeros(n, dtype=np.float64)
        sm = next_skip < n
        tm = next_take < n
        cont_skip[sm] = vmax[next_skip[sm]]
        cont_take[tm] = vmax[next_take[tm]]
        y = np.concatenate([reward_skip + gamma * cont_skip, reward_take + gamma * cont_take])
        weights = _fit_ridge(x, y, l2)
    return proto.QPolicy(weights=weights)


def _write_doc(report: dict[str, Any]) -> None:
    lines = [
        "# Portfolio RL Gate 2-Action Native Training - 2026-07-09",
        "",
        "Validation-only native FQI training from native rule-take transitions. OOS is evaluated once after the policy is frozen.",
        "",
        "| policy | split | PnL | MDD | MTM MDD | trades | WR |",
        "|---|---|---:|---:|---:|---:|---:|",
    ]
    for policy_name in ("rule_take_all", "native_rl_gate"):
        for split in ("validation", "oos_extended", "oos_frozen_q1_2026"):
            m = report["results"][policy_name][split]
            lines.append(f"| {policy_name} | {split} | {m['pnl']:.2f}% | {m['mdd']:.2f}% | {m['mark_to_market_mdd']:.2f}% | {m['trades']} | {m['wr']:.2%} |")
    lines.extend([
        "",
        "Promotion note: evaluation is native bar-by-bar and does not consume saved trade ledgers, but training only covers rule-visited validation transitions.",
        "",
    ])
    DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
    DOC_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    device = native.eth_retest.DEVICE
    print("stage=build_validation_world", flush=True)
    val_world = native._build_world("validation", device)
    print("stage=validation_rule_replay_for_transitions", flush=True)
    _rule_metrics, rule_ledger, _rule_diag = native._replay(val_world, None, take_all=True, device=device)
    print("stage=build_native_visited_transitions", flush=True)
    events = _build_transitions_from_native_rule_ledger(val_world, rule_ledger)
    events.to_csv(OUT_DIR / "validation_native_transition_events.csv", index=False)
    rule_ledger.to_csv(OUT_DIR / "validation_native_rule_take_transition_ledger.csv", index=False)
    print(f"stage=train_native_fqi events={len(events)}", flush=True)
    policy = _train_native_fqi(events)

    results = {"rule_take_all": {}, "native_rl_gate": {}}
    diagnostics: dict[str, Any] = {"validation_transition_events": int(len(events))}
    ledgers: dict[tuple[str, str], pd.DataFrame] = {}
    for split in ("validation", "oos"):
        print(f"stage=build_world split={split}", flush=True)
        world = val_world if split == "validation" else native._build_world("oos", device)
        for name, take_all in (("rule_take_all", True), ("native_rl_gate", False)):
            print(f"stage=replay split={split} policy={name}", flush=True)
            metrics, ledger, diag = native._replay(world, policy, take_all=take_all, device=device)
            key = "validation" if split == "validation" else "oos_extended"
            results[name][key] = metrics
            diagnostics[f"{name}_{key}"] = diag
            ledgers[(name, key)] = ledger
            if split == "oos":
                q1 = ledger.loc[pd.to_datetime(ledger["entry_timestamp"]) < pd.Timestamp("2026-04-01")].reset_index(drop=True) if not ledger.empty else ledger
                qm = native._compound_metrics(q1)
                qm["mark_to_market_mdd"] = qm["mdd"]
                results[name]["oos_frozen_q1_2026"] = qm
                ledgers[(name, "oos_frozen_q1_2026")] = q1
    for (name, split), ledger in ledgers.items():
        ledger.to_csv(OUT_DIR / f"{split}_{name}_ledger.csv", index=False)
    report = {
        "method": "portfolio_rl_gate_2action_native_validation_fqi",
        "training_data": "validation_native_rule_visited_transitions",
        "oos_usage": "reported_once_after_policy_training",
        "action_space": {"0": "SKIP", "1": "TAKE_TOP"},
        "asset_scores_validation_only": native.ASSET_SCORES,
        "rl_algorithm": {"name": "native_fitted_q_iteration_ridge_linear", "gamma": 0.97, "l2": 1.0, "iterations": 50},
        "policy_weights": policy.weights,
        "results": results,
        "diagnostics": diagnostics,
        "fresh_forward_bar_by_bar": True,
        "trade_ledgers_used_as_input": False,
        "saved_parent_exit_timestamps_used": False,
        "future_rows_used_for_entry": False,
        "native_training_transition_coverage": "rule_take_all_visited_validation_events_only",
        "promotion_grade": False,
    }
    (OUT_DIR / "report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2, default=_json_default) + "\n", encoding="utf-8")
    _write_doc(report)
    print(json.dumps({"report": str(OUT_DIR / "report.json"), "doc": str(DOC_PATH), "results": results}, ensure_ascii=False, indent=2, default=_json_default), flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
